### ISSUE TITLE
Path not being set properly when using metalsmith-in-place

### ISSUE THREAD

**Issue by jcrawford** [segmentio/metalsmith-collections#87] opened 2018-12-13 21:25 UTC
I am using both metalsmith-collections and metalsmith-in-place.  I am using markdown and Nunjucks so my files are in the format of filename.md.njk, I also have noticed that the path for the filenames when collections is run is being set using the *.md.njk format.

I have created my own articles plugin that modifies the navigation for my articles based on the file structure and also the path.  The issue I am having is that it appears I have to run metalsmith-in-place before metalsmith-collections in order to get the path to be correct so something like `articles/first-series/first-page.md.njk` rather than `articles/first-series/first-page.html`. 

It would be fine to run metalsmith-in-place before metalsmith-collections however when I do that then I do not get the path, next or previous links for my posts collection. See the attached screenshot for more information.  

Here is my build file as it currently sits.

```
/*jslint es6 */

/*
 * Metalsmith build file
 * Build site with `node build`
 */

'use strict';

const inplace = require('metalsmith-in-place');
const layouts = require('metalsmith-layouts');
const metalsmith = require('metalsmith');
const collections = require('metalsmith-collections');
const serve = require('metalsmith-serve');
const watch = require('metalsmith-watch');
const assets = require('metalsmith-assets');
const drafts = require('metalsmith-drafts');
const excerpts = require('metalsmith-excerpts');
const paginate = require('metalsmith-pager');
const archive = require('metalsmith-collections-archive');
const debug = require('metalsmith-debug-ui');


/* Local Plugins */
const utils = require('./lib/utils');
const articles = require('./lib/articles');
const permalinks = require('./lib/my-permalinks');

const templateConfig = {
    engineOptions: {
        highlight: utils.highlight,
        filters: {
            toUpper: utils.toUpper,
            spaceToDash: utils.spaceToDash
        }
    }
};

let ms = metalsmith(__dirname);

debug.patch(ms);

ms.metadata({
      site: {
        name: 'A Developers Blog',
        author: 'Joseph Crawford',
        description: 'A Developers Blog'
      }
    })
    .clean(true)
    .source('./src/')
    .destination('./build/')
    .use(collections({
      posts: {
        pattern: 'posts/**/*.njk',
        sortBy: 'date',
        reverse: true
      },
      articles: {
        pattern: ['articles/*.njk', 'articles/**/*.njk'],
        refer: false
      },
      reviews: {
        pattern: ['reviews/*.njk', 'reviews/**/*.njk'],
        sortBy: 'date',
        reverse: true
      }
    }))
    .use(archive({
      layout: 'archive.njk',
      rootLevel: false,
      collections: {
        'posts': true
      }
    }))
    .use(articles({
      collection: 'articles'
    }))
    .use(drafts())
    .use(excerpts())
    .use(paginate({
      collection: 'posts',
      elementsPerPage: 1,
      pagePattern: 'page/:PAGE/index.html',
      index: 'post.njk',
      paginationTemplatePath: '../layouts/partials/paginator.njk',
      layoutName: 'post.njk'
    }))
    .use(inplace(templateConfig))
    .use(layouts(templateConfig))
    .use(permalinks({
      relative: false,
      pattern: ":title",
      // each linkset defines a match, and any other desired option
      linksets: [{
        match: { collection: 'posts' },
        pattern: 'post/:date/:title',
      },{
        match: { collection: 'articles' },
        pattern: 'articles/:series.name/:title'
      },{
        match: { collection: 'reviews' },
        pattern: 'reviews/:date/:title'
      }]
    }))
    .use(assets({
      source: __dirname + '/assets/',
      destination: '.'
    }))
    .use(serve({
      port: 8080,
      verbose: true
    }))
    .use(watch({
      paths: {
        "${source}/**/*": true,
        "lib/**/*": "**/*",
        "layouts/**/*": "**/*"
      }
    }))
    .build(function (err) {
        if (err) {
          console.log(err);
            throw err;
        }
        console.log('Build finished!');
    });
```
**COLLECTIONS RUNNING FIRST**
<img width="634" alt="screen shot 2018-12-13 at 4 21 06 pm" src="https://user-images.githubusercontent.com/875341/49968371-a4314300-fef3-11e8-91ff-23481998f2b5.png">
<br/><br/>
**IN-PLACE RUNNING FIRST**
<img width="511" alt="screen shot 2018-12-13 at 4 21 37 pm" src="https://user-images.githubusercontent.com/875341/49968373-a4314300-fef3-11e8-97ec-9141504dd35e.png">
<br/><br/>
**MY BUILD DIRECTORY**
<img width="270" alt="screen shot 2018-12-13 at 4 24 23 pm" src="https://user-images.githubusercontent.com/875341/49968372-a4314300-fef3-11e8-9fe9-3fb423e0ed69.png">

**Comment by ismay** [comment] 2018-12-14 11:30
> I also have noticed that the path for the filenames when collections is run is being set using the *.md.njk format.

> I have created my own articles plugin that modifies the navigation for my articles based on the file structure and also the path. The issue I am having is that it appears I have to run metalsmith-in-place before metalsmith-collections in order to get the path to be correct so something like articles/first-series/first-page.md.njk rather than articles/first-series/first-page.html.

Hi @jcrawford. That is not a bug but expected behaviour. `metalsmith-in-place` changes the filenames after transforming. That doesn't mean that you won't be able to use collections or pagination though, just that you'll have to take this transformation into account. See how I'm doing it here for example: https://github.com/ismay/ismaywolff.nl/blob/master/metalsmith.js. I'll close this since it's not a bug or feature request. Hope that helps. For further help I recommend the slack channel, which is meant for support requests. Thanks!

**Closed by ismay** 2018-12-14 11:30 UTC

**Comment by jcrawford** [comment] 2018-12-14 15:02
I am not sure I see what you are doing differently, I am specifying the pattern in the collections options as well.

**Comment by jcrawford** [comment] 2018-12-14 15:55
@ismay I just found the slack channel :)

**Comment by ismay** [comment] 2018-12-14 16:04
Cool! 👍
